import Box from '@/components/Box'
import { CustomButton } from '@/components/CustomButton'
import Heading from '@/components/Heading/Heading'
import OTPInput from '@/components/InputOtp'
import Paragraph from '@/components/Paragraph/Paragraph'
import Text from '@/components/Text'
import TitleBar from '@/components/TitleBar/TitleBar'
import { StackParamsList } from '@/navigation/types'
import { useNavigation } from '@react-navigation/core'
import { StackNavigationProp } from '@react-navigation/stack'
import React, { useState } from 'react'
import { Dimensions, StyleSheet } from 'react-native'
import { RFValue } from 'react-native-responsive-fontsize'

const { height } = Dimensions.get('window')

const AuthenticationCode = () => {
    const navigation = useNavigation<StackNavigationProp<StackParamsList>>()
    const [code, setCode] = useState('');
    const [error, setError] = useState('');

    return (
        <Box flex={1} backgroundColor={'whiteColor'}>
            <TitleBar>
                <Box />
                <Box />
            </TitleBar>
            <Box style={{ paddingHorizontal: 20, marginTop: 40 }}>
                <Box style={{ marginTop: 30 }} />
                <Heading>
                    Authentication code
                </Heading>
                <Paragraph>
                    Enter the 6-digit code generated by the authentication app
                </Paragraph>
                <Box style={{ marginBottom: 30 }} />

                <OTPInput onCodeComplete={setCode} error={error} />
                <Box style={{ marginBottom: 30 }} />

                <CustomButton
                    label="Verify"
                    onPress={() => { }}
                    backgroundColor="primary"
                    labelProps={{ color: 'white', variant: 'regular14' }}
                    borderRadius="smm"
                // isLoading={isLoading || isSubmitting}
                // disabled={
                //     !(values.currentPassword && values.newPassword && values.confirmNewPassword)
                // }
                />
            </Box>
        </Box>
    )
}

export default AuthenticationCode

const styles = StyleSheet.create({
    title: {
        fontSize: RFValue(17, height),
        fontWeight: '600',
    },
})