import UsersPicture from "@/assets/svg/organizerPicture.svg"

const users = [
    {
        id: 1,
        userName: 'Ayo Mide',
        handle: '@username',
        university: 'Ambrose Ali University',
        isOnline: true,
        profileImage: <UsersPicture width={40} height={40} />,
        followText: 'Follow',
        isAttendee: true,
    },
    {
        id: 2,
        userName: 'Samuel James',
        handle: '@username',
        university: 'Ambrose Ali University',
        isOnline: false,
        profileImage: <UsersPicture width={40} height={40} />,
        followText: 'Follow',
        isAttendee: true,
    },
    {
        id: 3,
        userName: 'Oladipupo Taiwo',
        handle: '@username',
        university: 'Ambrose Ali University',
        isOnline: false,
        profileImage: <UsersPicture width={40} height={40} />,
        followText: 'Follow',
        isAttendee: true,
    },
    {
        id: 4,
        userName: 'Kuforiji Olawale',
        handle: '@username',
        university: 'Ambrose Ali University',
        isOnline: true,
        profileImage: <UsersPicture width={40} height={40} />,
        followText: 'Follow',
        isAttendee: true,
    },
    {
        id: 5,
        userName: 'John Mike',
        handle: '@username',
        university: 'Ambrose Ali University',
        isOnline: false,
        profileImage: <UsersPicture width={40} height={40} />,
        followText: 'Follow',
        isAttendee: true,
    },
    {
        id: 6,
        userName: 'Emmanuel Olusegun Okuns',
        handle: '@username',
        university: 'Ambrose Ali University',
        isOnline: true,
        profileImage: <UsersPicture width={40} height={40} />,
        followText: 'Follow',
        isAttendee: true,
    },
    {
        id: 7,
        userName: 'Fisayo Daniels',
        handle: '@username',
        university: 'Ambrose Ali University',
        isOnline: true,
        profileImage: <UsersPicture width={40} height={40} />,
        followText: 'Follow',
        isAttendee: true,
    },
    {
        id: 8,
        userName: 'Ayo Mide',
        handle: '@username',
        university: 'Ambrose Ali University',
        isOnline: true,
        profileImage: <UsersPicture width={40} height={40} />,
        followText: 'Follow',
        isAttendee: true,
    },
    {
        id: 9,
        userName: 'Ayo Mide',
        handle: '@username',
        university: 'Ambrose Ali University',
        isOnline: true,
        profileImage: <UsersPicture width={40} height={40} />,
        followText: 'Follow',
        isAttendee: true,
    },
    {
        id: 10,
        userName: 'Samuel James',
        handle: '@username',
        university: 'Ambrose Ali University',
        isOnline: false,
        profileImage: <UsersPicture width={40} height={40} />,
        followText: 'Follow',
        isAttendee: true,
    },
    {
        id: 11,
        userName: 'Oladipupo Taiwo',
        handle: '@username',
        university: 'Ambrose Ali University',
        isOnline: false,
        profileImage: <UsersPicture width={40} height={40} />,
        followText: 'Follow',
        isAttendee: true,
    },
    {
        id: 12,
        userName: 'Kuforiji Olawale',
        handle: '@username',
        university: 'Ambrose Ali University',
        isOnline: true,
        profileImage: <UsersPicture width={40} height={40} />,
        followText: 'Follow',
        isAttendee: true,
    },
    {
        id: 13,
        userName: 'John Mike',
        handle: '@username',
        university: 'Ambrose Ali University',
        isOnline: false,
        profileImage: <UsersPicture width={40} height={40} />,
        followText: 'Follow',
        isAttendee: true,
    },
    {
        id: 14,
        userName: 'Emmanuel Olusegun Okuns',
        handle: '@username',
        university: 'Ambrose Ali University',
        isOnline: true,
        profileImage: <UsersPicture width={40} height={40} />,
        followText: 'Follow',
        isAttendee: true,
    },
    {
        id: 15,
        userName: 'Fisayo Daniels',
        handle: '@username',
        university: 'Ambrose Ali University',
        isOnline: true,
        profileImage: <UsersPicture width={40} height={40} />,
        followText: 'Follow',
        isAttendee: true,
    },
    {
        id: 16,
        userName: 'Ayo Mide',
        handle: '@username',
        university: 'Ambrose Ali University',
        isOnline: true,
        profileImage: <UsersPicture width={40} height={40} />,
        followText: 'Follow',
        isAttendee: true,
    },


    {
        id: 17,
        userName: 'Lana Smith',
        handle: '@lana',
        university: 'Babcock University',
        profileImage: <UsersPicture width={40} height={40} />,
        isOrganizer: true

    },
    {
        id: 18,
        userName: 'John Doe',
        handle: '@john',
        university: 'Harvard University',
        profileImage: <UsersPicture width={40} height={40} />,
        isHost: true,
    },
];

export default users